import type { Metadata } from "next";
import ClientLayout from "./Clientlayout";

export const metadata: Metadata = {
  title: "FASCO",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
